import { StyleSheet } from "react-native";
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from '../../utils/responsive';

export const lightTheme = {
  background: "#f8fafc",
  card: "#ffffff",
  inputBackground: "#ffffff",
  text: "#1e293b",
  textSecondary: "#64748b",
  border: "#e2e8f0",
  primary: "#3b82f6",
  success: "#10b981",
  error: "#ef4444",
  shadow: "#000",
};

export const darkTheme = {
  background: "#0f172a",
  card: "#1e293b",
  inputBackground: "#1e293b",
  text: "#f1f5f9",
  textSecondary: "#94a3b8",
  border: "#334155",
  primary: "#3b82f6",
  success: "#10b981",
  error: "#ef4444",
  shadow: "#000",
};

export const createAuthStyles = (theme: typeof lightTheme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
      paddingHorizontal: wp("6%"),
    },
    scrollContainer: {
      flexGrow: 1,
      justifyContent: "center",
      paddingVertical: hp("5%"),
    },
    headerContainer: {
      alignItems: "center",
      marginBottom: hp("5%"),
    },
    title: {
      fontSize: wp("8%"),
      fontWeight: "700",
      color: theme.text,
      textAlign: "center",
      marginBottom: hp("1%"),
    },
    subtitle: {
      fontSize: wp("4%"),
      color: theme.textSecondary,
      textAlign: "center",
    },
    inputContainer: {
      marginBottom: hp("2.5%"),
    },
    input: {
      backgroundColor: theme.inputBackground,
      borderColor: theme.border,
      borderRadius: wp("3%"),
      paddingVertical: hp("2%"),
      paddingHorizontal: wp("4%"),
      fontSize: wp("4%"),
      color: theme.text,
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    inputFocused: {
      borderColor: theme.primary,
      shadowColor: theme.primary,
      shadowOpacity: 0.15,
    },
    inputError: {
      borderColor: theme.error,
    },
    passwordContainer: {
      position: "relative",
    },
    passwordInput: {
      backgroundColor: theme.card,
      borderWidth: 2,
      borderColor: theme.border,
      borderRadius: wp("3%"),
      paddingVertical: hp("2%"),
      paddingHorizontal: wp("4%"),
      paddingRight: wp("13%"),
      fontSize: wp("4%"),
      color: theme.text,
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    eyeButton: {
      position: "absolute",
      right: wp("4%"),
      top: "50%",
      marginTop: hp("-1.5%"),
      padding: wp("1%"),
      borderRadius: wp("1.5%"),
    },
    button: {
      backgroundColor: theme.primary,
      paddingVertical: hp("2%"),
      paddingHorizontal: wp("6%"),
      borderRadius: wp("3%"),
      alignItems: "center",
      justifyContent: "center",
      marginVertical: hp("1.5%"),
      minHeight: hp("6.5%"),
      shadowColor: theme.primary,
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 4,
    },
    primary: {
      backgroundColor: theme.primary,
    },
    secondary: {
      backgroundColor: "transparent",
      borderWidth: 2,
      borderColor: theme.primary,
      shadowOpacity: 0,
      elevation: 0,
    },
    disabled: {
      backgroundColor: theme.textSecondary,
      shadowOpacity: 0,
      elevation: 0,
    },
    buttonText: {
      fontSize: wp("4%"),
      fontWeight: "600",
      textAlign: "center",
      letterSpacing: 0.5,
    },
    primaryText: {
      color: "#ffffff",
    },
    secondaryText: {
      color: theme.primary,
    },
    linkContainer: {
      alignItems: "center",
      marginTop: hp("3%"),
    },
    linkText: {
      color: theme.primary,
      fontSize: wp("4%"),
      fontWeight: "500",
    },
    errorContainer: {
      marginTop: hp("0.5%"),
      marginBottom: hp("1%"),
    },
    errorText: {
      color: theme.error,
      fontSize: wp("3.5%"),
      fontWeight: "500",
    },
    successContainer: {
      marginTop: hp("0.5%"),
      marginBottom: hp("1%"),
    },
    successText: {
      color: theme.success,
      fontSize: wp("3.5%"),
      fontWeight: "500",
    },
    imagePicker: {
      backgroundColor: theme.primary,
      paddingVertical: hp("1.5%"),
      paddingHorizontal: wp("5%"),
      borderRadius: wp("2.5%"),
      alignItems: "center",
      justifyContent: "center",
      marginBottom: hp("2%"),
      shadowColor: theme.primary,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.15,
      shadowRadius: 4,
      elevation: 2,
      flexDirection: "row",
      minHeight: hp("5.5%"),
    },
    imagePickerText: {
      color: "#ffffff",
      fontSize: wp("3.7%"),
      fontWeight: "600",
      marginLeft: wp("1.5%"),
    },
    profileImageContainer: {
      alignItems: "center",
      marginTop: hp("2%"),
      marginBottom: hp("2.5%"),
    },
    profileImage: {
      width: wp("30%"),
      height: wp("30%"),
      borderRadius: wp("15%"),
      borderWidth: wp("1%"),
      borderColor: theme.primary,
      marginTop: hp("1.5%"),
    },
    formSection: {
      marginBottom: hp("3%"),
    },
    sectionTitle: {
      fontSize: wp("4.5%"),
      fontWeight: "600",
      color: theme.text,
      marginBottom: hp("2%"),
    },
    themeToggle: {
      position: "absolute",
      top: hp("6.2%"),
      right: wp("5%"),
      width: wp("11%"),
      height: wp("11%"),
      borderRadius: wp("5.5%"),
      backgroundColor: theme.card,
      borderWidth: 2,
      borderColor: theme.border,
      justifyContent: "center",
      alignItems: "center",
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
      zIndex: 1000,
    },
    mapContainer: {
      flex: 1,
    },
    mapHeader: {
      backgroundColor: theme.card,
      paddingTop: hp("6.2%"),
      paddingBottom: hp("2%"),
      paddingHorizontal: wp("6%"),
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    mapHeaderContent: {
      flexDirection: "row",
      alignItems: "center",
    },
    mapBackButton: {
      width: wp("10%"),
      height: wp("10%"),
      borderRadius: wp("5%"),
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.border,
      justifyContent: "center",
      alignItems: "center",
      marginRight: wp("4%"),
    },
    mapHeaderTextContainer: {
      flex: 1,
    },
    mapHeaderTitle: {
      fontSize: wp("5%"),
      fontWeight: "700",
      color: theme.text,
    },
    mapHeaderSubtitle: {
      fontSize: wp("3.5%"),
      color: theme.textSecondary,
      marginTop: hp("0.25%"),
    },
    coordinatesOverlay: {
      position: "absolute",
      top: hp("2.5%"),
      left: wp("5%"),
      right: wp("5%"),
      backgroundColor: theme.card,
      padding: wp("4%"),
      borderRadius: wp("3%"),
      borderWidth: 1,
      borderColor: theme.border,
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 5,
    },
    coordinatesLabel: {
      fontSize: wp("3.5%"),
      fontWeight: "600",
      color: theme.textSecondary,
      marginBottom: hp("0.5%"),
    },
    coordinatesText: {
      fontSize: wp("4%"),
      fontWeight: "500",
      color: theme.text,
      fontFamily: "monospace",
    },
    actionButtonsContainer: {
      position: "absolute",
      bottom: hp("3.7%"),
      left: wp("5%"),
      right: wp("5%"),
    },
    buttonRow: {
      flexDirection: "row",
      gap: wp("3%"),
    },
    mapButton: {
      paddingVertical: hp("1.7%"),
      paddingHorizontal: wp("5%"),
      borderRadius: wp("3%"),
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 4,
    },
    currentLocationButton: {
      backgroundColor: theme.textSecondary,
      flex: 1,
    },
    confirmButton: {
      backgroundColor: theme.primary,
      flex: 2,
    },
    confirmButtonDisabled: {
      backgroundColor: theme.border,
      shadowOpacity: 0,
      elevation: 0,
    },
    mapButtonText: {
      color: "#ffffff",
      fontSize: wp("4%"),
      fontWeight: "600",
      marginLeft: wp("2%"),
    },
  });

const authStyles = createAuthStyles(lightTheme);
export default authStyles;
